-- Autogenerated file.  Do not edit.  All changes will be lost
--
-- Definition of Frost Deathknight

DestroDummies.classDeathknightFrost = DestroDummies.lastClassVal + 1;
DestroDummies.lastClassVal = DestroDummies.lastClassVal + 1;

local mIndexBase = DestroDummies.lastMutexIndex;

DestroDummies.mutex[mIndexBase + 1] = {};
DestroDummies.mutex[mIndexBase + 1].clipCombat = 0;
DestroDummies.mutex[mIndexBase + 1].clipOOCombat = 0;
DestroDummies.mutex[mIndexBase + 1][1] = DestroDummies:xlateString("Horn of Winter")
DestroDummies.mutex[mIndexBase + 1][2] = DestroDummies:xlateString("Strength of Earth Totem")
DestroDummies.mutex[mIndexBase + 1][3] = DestroDummies:xlateString("Battle Shout")
DestroDummies.mutex[mIndexBase + 1][4] = DestroDummies:xlateString("Roar of Courage")
DestroDummies.mutex[mIndexBase + 1].count = 4;
DestroDummies.mutex[mIndexBase + 2] = {};
DestroDummies.mutex[mIndexBase + 2].clipCombat = 5;
DestroDummies.mutex[mIndexBase + 2].clipOOCombat = 5;
DestroDummies.mutex[mIndexBase + 2][1] = DestroDummies:xlateString("Mark of the Wild")
DestroDummies.mutex[mIndexBase + 2][2] = DestroDummies:xlateString("Blessing of Kings")
DestroDummies.mutex[mIndexBase + 2].count = 2;
DestroDummies.mutex[mIndexBase + 3] = {};
DestroDummies.mutex[mIndexBase + 3].clipCombat = 1.50;
DestroDummies.mutex[mIndexBase + 3].clipOOCombat = 1.50;
DestroDummies.mutex[mIndexBase + 3][1] = DestroDummies:xlateString("Mangle")
DestroDummies.mutex[mIndexBase + 3][2] = DestroDummies:xlateString("Trauma")
DestroDummies.mutex[mIndexBase + 3].count = 2;
DestroDummies.mutex[mIndexBase + 4] = {};
DestroDummies.mutex[mIndexBase + 4].clipCombat = 0;
DestroDummies.mutex[mIndexBase + 4].clipOOCombat = 0;
DestroDummies.mutex[mIndexBase + 4][1] = DestroDummies:xlateString("Faerie Fire")
DestroDummies.mutex[mIndexBase + 4][2] = DestroDummies:xlateString("Faerie Swarm")
DestroDummies.mutex[mIndexBase + 4][3] = DestroDummies:xlateString("Tear Armor")
DestroDummies.mutex[mIndexBase + 4][4] = DestroDummies:xlateString("Corrosive Spit")
DestroDummies.mutex[mIndexBase + 4][5] = DestroDummies:xlateString("Expose Armor")
DestroDummies.mutex[mIndexBase + 4][6] = DestroDummies:xlateString("Sunder Armor")
DestroDummies.mutex[mIndexBase + 4].count = 6;
local varHaveGoHB;
local varHaveMotFW;
local function preCombat()
    varHaveGoHB = DestroDummies:utilHasGlyph(DestroDummies:xlateString("Glyph of Howling Blast"))
    varHaveMotFW = DestroDummies:utilTalentCount(DestroDummies:xlateString("Might of the Frozen Wastes"))
end
DestroDummies.registry.preCombat[DestroDummies.classDeathknightFrost] = preCombat;

local function PickCombat()
    DestroDummies:analysisInit();
    if (DestroDummies:spellReady(DestroDummies:xlateString("Raise Dead"))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Raise Dead"), 1);
    end;
    if (DestroDummies:spellReady(DestroDummies:xlateString("Pillar of Frost"))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Pillar of Frost"), 2);
    end;
    local vardisFrost;
    local vardisBP;
    vardisFrost = DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Frost Fever"), 0)
    vardisBP = DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Blood Plague"), 0)
    if (not (DestroDummies:utilBuff(DestroDummies:xlateString("Frost Presence"), 0, "player", "HELPFUL", nil))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Frost Presence"));
    end;
    if (GetInventoryItemID("player", DestroDummies.offhandSlotNum) ~= nil) then
        if ((DestroDummies:utilHealth("target")) < (35)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Soul Reaper"));
        end;
        if ((not (vardisFrost)) and (not (vardisBP))) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Outbreak"));
        end;
        if ((not (vardisFrost)) and (varHaveGoHB)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Howling Blast"));
        end;
        if ((not (vardisFrost)) and (DestroDummies:utilHaveRunes(0, 1, 0))) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Icy Touch"));
        end;
        if (not (vardisBP)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Plague Strike"));
        end;
        if (DestroDummies:utilBuff(DestroDummies:xlateString("Killing Machine"), 0, "player", "HELPFUL", nil)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Frost Strike"));
        end;
        if (DestroDummies:spellReady(DestroDummies:xlateString("Death and Decay"))) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Death and Decay"));
        end;
        if ((((DestroDummies:utilBuff(DestroDummies:xlateString("Killing Machine"), 0, "player", "HELPFUL", nil)) and (vardisFrost)) and (vardisBP)) and ((DestroDummies:utilRuneCount(2)) == (2))) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Obliterate"));
        end;
        if ((((DestroDummies:unitPowerAfterCast() * 100) / UnitPowerMax("player"))) >= (100)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Frost Strike"));
        end;
        if (DestroDummies:utilBuff(DestroDummies:xlateString("Freezing Fog"), 0, "player", "HELPFUL", nil)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Howling Blast"));
        end;
        if (DestroDummies:utilHaveRunes(0, 1, 1)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Obliterate"));
        end;
        DestroDummies:analysisAdd(DestroDummies:xlateString("Frost Strike"));
        DestroDummies:analysisAdd(DestroDummies:xlateString("Howling Blast"));
        DestroDummies:analysisAdd(DestroDummies:xlateString("Horn of Winter"));
    else
        if ((DestroDummies:utilHealth("target")) < (35)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Soul Reaper"));
        end;
        if (((DestroDummies:utilBuff(DestroDummies:xlateString("Killing Machine"), 0, "player", "HELPFUL", nil)) and (vardisFrost)) and (vardisBP)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Obliterate"));
        end;
        if ((not (vardisFrost)) and (not (vardisBP))) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Outbreak"));
        end;
        if ((not (vardisFrost)) and (varHaveGoHB)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Howling Blast"));
        end;
        if ((not (vardisFrost)) and (DestroDummies:utilHaveRunes(0, 1, 0))) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Icy Touch"));
        end;
        if (not (vardisBP)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Plague Strike"));
        end;
        if (DestroDummies:utilBuff(DestroDummies:xlateString("Killing Machine"), 0, "player", "HELPFUL", nil)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Frost Strike"));
        end;
        if (DestroDummies:utilBuff(DestroDummies:xlateString("Freezing Fog"), 0, "player", "HELPFUL", nil)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Howling Blast"));
        end;
        DestroDummies:analysisAdd(DestroDummies:xlateString("Obliterate"));
        DestroDummies:analysisAdd(DestroDummies:xlateString("Frost Strike"));
        DestroDummies:analysisAdd(DestroDummies:xlateString("Horn of Winter"));
    end;
    return DestroDummies:analysisPick(nil, nil);
end;

local function PickNoCombat()
    DestroDummies:analysisInit();
    if (not (DestroDummies:utilBuff(DestroDummies:xlateString("Frost Presence"), 0, "player", "HELPFUL", nil))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Frost Presence"));
    end;
    if ((not (DestroDummies:utilMxBuff(mIndexBase + 1))) and (not (IsMounted()))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Horn of Winter"));
    end;
    return DestroDummies:analysisPick(nil, nil);
end;

-- populate our registries
DestroDummies.registry.decideCombat[DestroDummies.classDeathknightFrost] = PickCombat;
DestroDummies.registry.decideNoCombat[DestroDummies.classDeathknightFrost] = PickNoCombat;
DestroDummies.lastMutexIndex = mIndexBase + 4;
