-- Autogenerated file.  Do not edit.  All changes will be lost
--
-- Definition of Unholy Deathknight

DestroDummies.classDeathknightUnholy = DestroDummies.lastClassVal + 1;
DestroDummies.lastClassVal = DestroDummies.lastClassVal + 1;

local mIndexBase = DestroDummies.lastMutexIndex;

DestroDummies.mutex[mIndexBase + 1] = {};
DestroDummies.mutex[mIndexBase + 1].clipCombat = 0;
DestroDummies.mutex[mIndexBase + 1].clipOOCombat = 0;
DestroDummies.mutex[mIndexBase + 1][1] = DestroDummies:xlateString("Horn of Winter")
DestroDummies.mutex[mIndexBase + 1][2] = DestroDummies:xlateString("Strength of Earth Totem")
DestroDummies.mutex[mIndexBase + 1][3] = DestroDummies:xlateString("Battle Shout")
DestroDummies.mutex[mIndexBase + 1][4] = DestroDummies:xlateString("Roar of Courage")
DestroDummies.mutex[mIndexBase + 1].count = 4;
DestroDummies.mutex[mIndexBase + 2] = {};
DestroDummies.mutex[mIndexBase + 2].clipCombat = 5;
DestroDummies.mutex[mIndexBase + 2].clipOOCombat = 5;
DestroDummies.mutex[mIndexBase + 2][1] = DestroDummies:xlateString("Mark of the Wild")
DestroDummies.mutex[mIndexBase + 2][2] = DestroDummies:xlateString("Blessing of Kings")
DestroDummies.mutex[mIndexBase + 2].count = 2;
DestroDummies.mutex[mIndexBase + 3] = {};
DestroDummies.mutex[mIndexBase + 3].clipCombat = 1.50;
DestroDummies.mutex[mIndexBase + 3].clipOOCombat = 1.50;
DestroDummies.mutex[mIndexBase + 3][1] = DestroDummies:xlateString("Mangle")
DestroDummies.mutex[mIndexBase + 3][2] = DestroDummies:xlateString("Trauma")
DestroDummies.mutex[mIndexBase + 3].count = 2;
DestroDummies.mutex[mIndexBase + 4] = {};
DestroDummies.mutex[mIndexBase + 4].clipCombat = 0;
DestroDummies.mutex[mIndexBase + 4].clipOOCombat = 0;
DestroDummies.mutex[mIndexBase + 4][1] = DestroDummies:xlateString("Faerie Fire")
DestroDummies.mutex[mIndexBase + 4][2] = DestroDummies:xlateString("Faerie Swarm")
DestroDummies.mutex[mIndexBase + 4][3] = DestroDummies:xlateString("Tear Armor")
DestroDummies.mutex[mIndexBase + 4][4] = DestroDummies:xlateString("Corrosive Spit")
DestroDummies.mutex[mIndexBase + 4][5] = DestroDummies:xlateString("Expose Armor")
DestroDummies.mutex[mIndexBase + 4][6] = DestroDummies:xlateString("Sunder Armor")
DestroDummies.mutex[mIndexBase + 4].count = 6;
local function PickCombat()
    DestroDummies:analysisInit();
    if (DestroDummies:spellReady(DestroDummies:xlateString("Summon Gargoyle"))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Summon Gargoyle"), 1);
    end;
    if (DestroDummies:spellReady(DestroDummies:xlateString("Bone Shield"))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Bone Shield"), 2);
    end;
    if ((DestroDummies:utilHealth("target")) < (35)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Soul Reaper"));
    end;
    if (not (DestroDummies:utilBuff(DestroDummies:xlateString("Unholy Presence"), 0, "player", "HELPFUL", nil))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Unholy Presence"));
    end;
    if (not (UnitExists("pet"))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Raise Dead"));
    end;
    if (((not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Blood Plague"), 0))) and (not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Frost Fever"), 0))))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Outbreak"));
    end;
    if (not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Blood Plague"), 0))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Plague Strike"));
    end;
    if (not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Frost Fever"), 0))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Icy Touch"));
    end;
    if (DestroDummies:spellReady(DestroDummies:xlateString("Dark Transformation"))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Dark Transformation"));
    end;
    if ((DestroDummies:utilRuneCount(2)) == (2)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Death and Decay"));
    end;
    if ((DestroDummies:utilRuneCount(2)) == (2)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Scourge Strike"));
    end;
    if (((DestroDummies:utilRuneCount(1)) == (2)) and ((DestroDummies:utilRuneCount(3)) == (2))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Festering Strike"));
    end;
    if (((((DestroDummies:unitPowerAfterCast() * 100) / UnitPowerMax("player"))) > (90)) or (DestroDummies:utilBuff(DestroDummies:xlateString("Sudden Doom"), 0, "player", "HELPFUL", nil))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Death Coil"));
    end;
    if (DestroDummies:utilHaveRunes(0, 0, 1)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Scourge Strike"));
    end;
    if (DestroDummies:utilHaveRunes(1, 1, 0)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Festering Strike"));
    end;
    DestroDummies:analysisAdd(DestroDummies:xlateString("Horn of Winter"));
    return DestroDummies:analysisPick("Empower Rune Weapon", nil);
end;

local function PickNoCombat()
    DestroDummies:analysisInit();
    if (not (DestroDummies:utilBuff(DestroDummies:xlateString("Unholy Presence"), 0, "player", "HELPFUL", nil))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Unholy Presence"));
    end;
    if ((not (DestroDummies:utilMxBuff(mIndexBase + 1))) and (not (IsMounted()))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Horn of Winter"));
    end;
    if (((DestroDummies:spellReady(DestroDummies:xlateString("Raise Dead"))) and (not (UnitExists("pet")))) and (not (IsMounted()))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Raise Dead"));
    end;
    return DestroDummies:analysisPick(nil, nil);
end;

-- populate our registries
DestroDummies.registry.decideCombat[DestroDummies.classDeathknightUnholy] = PickCombat;
DestroDummies.registry.decideNoCombat[DestroDummies.classDeathknightUnholy] = PickNoCombat;
DestroDummies.lastMutexIndex = mIndexBase + 4;
