-- Autogenerated file.  Do not edit.  All changes will be lost
--
-- Definition of Fire Mage

DestroDummies.classMageFire = DestroDummies.lastClassVal + 1;
DestroDummies.lastClassVal = DestroDummies.lastClassVal + 1;

local mIndexBase = DestroDummies.lastMutexIndex;

DestroDummies.mutex[mIndexBase + 1] = {};
DestroDummies.mutex[mIndexBase + 1].clipOOCombat = 300;
DestroDummies.mutex[mIndexBase + 1].clipCombat = 5;
DestroDummies.mutex[mIndexBase + 1][1] = DestroDummies:xlateString("Molten Armor")
DestroDummies.mutex[mIndexBase + 1][2] = DestroDummies:xlateString("Mage Armor")
DestroDummies.mutex[mIndexBase + 1][3] = DestroDummies:xlateString("Frost Armor")
DestroDummies.mutex[mIndexBase + 1].count = 3;
DestroDummies.mutex[mIndexBase + 2] = {};
DestroDummies.mutex[mIndexBase + 2].clipOOCombat = 300;
DestroDummies.mutex[mIndexBase + 2].clipCombat = 5;
DestroDummies.mutex[mIndexBase + 2][1] = DestroDummies:xlateString("Arcane Brilliance")
DestroDummies.mutex[mIndexBase + 2][2] = DestroDummies:xlateString("Dalaran Brilliance")
DestroDummies.mutex[mIndexBase + 2].count = 2;
local function PickCombat()
    DestroDummies:analysisInit();
    if not (DestroDummies:utilMxBuffByMe(mIndexBase + 1)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Molten Armor"));
        DestroDummies:analysisAdd(DestroDummies:xlateString("Mage Armor"));
    end;
    if (not (DestroDummies:utilBuff(DestroDummies:xlateString("Combustion"), 0, "player", "HELPFUL", nil))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Combustion"), 0);
    end;
    if (not (DestroDummies:utilBuff(DestroDummies:xlateString("Incanter's Ward"), 0, "player", "HELPFUL", nil))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Incanter's Ward"), 0);
    end;
    if (DestroDummies:spellReady(DestroDummies:xlateString("Mirror Image"))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Mirror Image"), 0);
    end;
    if (DestroDummies:utilBuff(DestroDummies:xlateString("Heating Up"), 0, "player", "HELPFUL", nil)) and (DestroDummies:utilBuff(DestroDummies:xlateString("Hot Streak"), 0, "player", "HELPFUL", nil)) then
        if (not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Living Bomb"), 0))) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Living Bomb"));
        end;
        DestroDummies:analysisAdd(DestroDummies:xlateString("Fireball"));
        DestroDummies:analysisAdd(DestroDummies:xlateString("Pyroblast"));
    end;
    if (DestroDummies:utilBuff(DestroDummies:xlateString("Heating Up"), 0, "player", "HELPFUL", nil)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Inferno Blast"));
    end;
    if (not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Living Bomb"), 0))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Living Bomb"));
    end;
    if (not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Nether Tempest"), 0))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Nether Tempest"));
    end;
    if (not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Frost Bomb"), 0))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Frost Bomb"));
    end;
    if (DestroDummies:utilBuff(DestroDummies:xlateString("Hot Streak"), 0, "player", "HELPFUL", nil)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Pyroblast"));
    end;
    if (not (DestroDummies:utilMxBuff(mIndexBase + 2))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Arcane Brilliance"));
    end;
    DestroDummies:analysisAdd(DestroDummies:xlateString("Frostfire Bolt"));
    DestroDummies:analysisAdd(DestroDummies:xlateString("Fireball"));
    return DestroDummies:analysisPick("Evocation", nil);
end;

local function PickNoCombat()
    DestroDummies:analysisInit();
    if not (DestroDummies:utilMxBuffByMe(mIndexBase + 1)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Molten Armor"));
        DestroDummies:analysisAdd(DestroDummies:xlateString("Mage Armor"));
    end;
    if (not (DestroDummies:utilMxBuff(mIndexBase + 2))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Arcane Brilliance"));
    end;
    return DestroDummies:analysisPick(nil, nil);
end;

-- populate our registries
DestroDummies.registry.decideCombat[DestroDummies.classMageFire] = PickCombat;
DestroDummies.registry.decideNoCombat[DestroDummies.classMageFire] = PickNoCombat;
DestroDummies.lastMutexIndex = mIndexBase + 2;
