-- Autogenerated file.  Do not edit.  All changes will be lost
--
-- Definition of Frost Mage

DestroDummies.classMageFrost = DestroDummies.lastClassVal + 1;
DestroDummies.lastClassVal = DestroDummies.lastClassVal + 1;

local mIndexBase = DestroDummies.lastMutexIndex;

DestroDummies.mutex[mIndexBase + 1] = {};
DestroDummies.mutex[mIndexBase + 1].clipOOCombat = 300;
DestroDummies.mutex[mIndexBase + 1].clipCombat = 5;
DestroDummies.mutex[mIndexBase + 1][1] = DestroDummies:xlateString("Molten Armor")
DestroDummies.mutex[mIndexBase + 1][2] = DestroDummies:xlateString("Mage Armor")
DestroDummies.mutex[mIndexBase + 1][3] = DestroDummies:xlateString("Frost Armor")
DestroDummies.mutex[mIndexBase + 1].count = 3;
DestroDummies.mutex[mIndexBase + 2] = {};
DestroDummies.mutex[mIndexBase + 2].clipOOCombat = 300;
DestroDummies.mutex[mIndexBase + 2].clipCombat = 5;
DestroDummies.mutex[mIndexBase + 2][1] = DestroDummies:xlateString("Arcane Brilliance")
DestroDummies.mutex[mIndexBase + 2][2] = DestroDummies:xlateString("Dalaran Brilliance")
DestroDummies.mutex[mIndexBase + 2].count = 2;
local function PickCombat()
    DestroDummies:analysisInit();
    if ((not (HasPetUI())) and (DestroDummies:spellReady(DestroDummies:xlateString("Summon Water Elemental")))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Summon Water Elemental"), 0);
    end;
    if (not (DestroDummies:utilMxBuff(mIndexBase + 2))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Arcane Brilliance"), 0);
    end;
    if not (DestroDummies:utilMxBuffByMe(mIndexBase + 1)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Molten Armor"));
        DestroDummies:analysisAdd(DestroDummies:xlateString("Mage Armor"));
    end;
    DestroDummies:analysisAdd(DestroDummies:xlateString("Frostfire Orb"));
    if DestroDummies:utilBuff(DestroDummies:xlateString("Fingers of Frost"), 0, "player", "HELPFUL", nil) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Deep Freeze"));
        if (DestroDummies:utilBuff(DestroDummies:xlateString("Brain Freeze"), 0, "player", "HELPFUL", nil)) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Frostfire Bolt"));
        end;
        DestroDummies:analysisAdd(DestroDummies:xlateString("Ice Lance"));
    else
        if (HasPetUI()) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Freeze"));
        end;
    end;
    DestroDummies:analysisAdd(DestroDummies:xlateString("Frostbolt"));
    return DestroDummies:analysisPick("Evocation", nil);
end;

local function PickNoCombat()
    DestroDummies:analysisInit();
    if not (DestroDummies:utilMxBuffByMe(mIndexBase + 1)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Molten Armor"));
        DestroDummies:analysisAdd(DestroDummies:xlateString("Mage Armor"));
    end;
    if (not (DestroDummies:utilMxBuff(mIndexBase + 2))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Arcane Brilliance"));
    end;
    return DestroDummies:analysisPick(nil, nil);
end;

-- populate our registries
DestroDummies.registry.decideCombat[DestroDummies.classMageFrost] = PickCombat;
DestroDummies.registry.decideNoCombat[DestroDummies.classMageFrost] = PickNoCombat;
DestroDummies.lastMutexIndex = mIndexBase + 2;
