-- Autogenerated file.  Do not edit.  All changes will be lost
--
-- Definition of Windwalker Monk

DestroDummies.classMonkWindwalker = DestroDummies.lastClassVal + 1;
DestroDummies.lastClassVal = DestroDummies.lastClassVal + 1;

local mIndexBase = DestroDummies.lastMutexIndex;

local function PickCombat()
    DestroDummies:analysisInit();
    local vartptime;
    local vartecount;
    local vartetime;
    vartptime = DestroDummies:utilBuffInfo(DestroDummies:xlateString("Tiger Power"), false, "player")
    vartetime, vartecount = DestroDummies:utilBuffInfo(DestroDummies:xlateString("Tigereye Brew"), false, "player")
    if ((not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Rising Sun Kick"), 0))) and (DestroDummies:spellReady(DestroDummies:xlateString("Rising Sun Kick")))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Rising Sun Kick"));
    end;
    if (((vartptime) < (3)) and (DestroDummies:spellReady(DestroDummies:xlateString("Tiger Palm")))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Tiger Palm"));
    end;
    if ((((DestroDummies:unitPowerAfterCast() * 100) / UnitPowerMax("player"))) > (80)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Jab"));
    end;
    if ((vartecount) == (10)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Tigereye Brew"));
    end;
    DestroDummies:analysisAdd(DestroDummies:xlateString("Rising Sun Kick"));
    DestroDummies:analysisAdd(DestroDummies:xlateString("Fists of Fury"));
    if (DestroDummies:utilBuff(DestroDummies:xlateString("Combo Breaker"), 0, "player", "HELPFUL", nil)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Blackout Kick"));
    end;
    if (DestroDummies:utilBuff(DestroDummies:xlateString("Combo Breaker"), 0, "player", "HELPFUL", nil)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Tiger Palm"));
    end;
    if (DestroDummies:spellReady(DestroDummies:xlateString("Blackout Kick"))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Blackout Kick"));
    end;
    DestroDummies:analysisAdd(DestroDummies:xlateString("Jab"));
    DestroDummies:analysisAdd(DestroDummies:xlateString("Flying Serpent Kick"));
    return DestroDummies:analysisPick("Energizing Brew", nil);
end;

local function PickNoCombat()
    DestroDummies:analysisInit();
    return DestroDummies:analysisPick(nil, nil);
end;

-- populate our registries
DestroDummies.registry.decideCombat[DestroDummies.classMonkWindwalker] = PickCombat;
DestroDummies.registry.decideNoCombat[DestroDummies.classMonkWindwalker] = PickNoCombat;
DestroDummies.lastMutexIndex = mIndexBase + 0;
