-- Autogenerated file.  Do not edit.  All changes will be lost
--
-- Definition of Elemental Shaman

DestroDummies.classShamanElemental = DestroDummies.lastClassVal + 1;
DestroDummies.lastClassVal = DestroDummies.lastClassVal + 1;

local mIndexBase = DestroDummies.lastMutexIndex;

DestroDummies.mutex[mIndexBase + 1] = {};
DestroDummies.mutex[mIndexBase + 1].clipOOCombat = 60;
DestroDummies.mutex[mIndexBase + 1].clipCombat = 5;
DestroDummies.mutex[mIndexBase + 1][1] = DestroDummies:xlateString("Lightning Shield")
DestroDummies.mutex[mIndexBase + 1][2] = DestroDummies:xlateString("Water Shield")
DestroDummies.mutex[mIndexBase + 1].count = 2;
local function PickCombat()
    DestroDummies:analysisInit();
    local clipFlametongueWeapon = 1;
    local clipFlameShock = 1;
    if (DestroDummies:spellReady(DestroDummies:xlateString("Heroism"))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Heroism"), 1);
    end;
    if (DestroDummies:spellReady(DestroDummies:xlateString("Bloodlust"))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Bloodlust"), 1);
    end;
    if (DestroDummies:spellReady(DestroDummies:xlateString("Fire Elemental Totem"))) then
        DestroDummies:altRecommend(DestroDummies:xlateString("Fire Elemental Totem"), 3);
    end;
    if (not (DestroDummies:utilWeaponEnhance(clipFlametongueWeapon))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Flametongue Weapon"));
    end;
    if (not (DestroDummies:utilMxBuff(mIndexBase + 1))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Lightning Shield"));
    end;
    local varlsTime;
    local varlsCount;
    varlsTime, varlsCount = DestroDummies:utilBuffInfo(DestroDummies:xlateString("Lightning Shield"), false, "player")
    if (not (DestroDummies:utilTotemType(1))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Searing Totem"));
    end;
    if (not (DestroDummies:utilDebuffByMe(DestroDummies:xlateString("Flame Shock"), clipFlameShock))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Flame Shock"));
    end;
    DestroDummies:analysisAdd(DestroDummies:xlateString("Lava Burst"));
    if ((varlsCount) >= (7)) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Earth Shock"));
    end;
    DestroDummies:analysisAdd(DestroDummies:xlateString("Lightning Bolt"));
    return DestroDummies:analysisPick(nil, nil);
end;

local function PickNoCombat()
    DestroDummies:analysisInit();
    local clipFlametongueWeapon = (5) * (60);
    if not (IsMounted()) then
        if (not (DestroDummies:utilWeaponEnhance(clipFlametongueWeapon))) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Flametongue Weapon"));
        end;
        if (not (DestroDummies:utilMxBuff(mIndexBase + 1))) then
            DestroDummies:analysisAdd(DestroDummies:xlateString("Lightning Shield"));
        end;
    end;
    return DestroDummies:analysisPick(nil, nil);
end;

-- populate our registries
DestroDummies.registry.decideCombat[DestroDummies.classShamanElemental] = PickCombat;
DestroDummies.registry.decideNoCombat[DestroDummies.classShamanElemental] = PickNoCombat;
DestroDummies.lastMutexIndex = mIndexBase + 1;
