-- Autogenerated file.  Do not edit.  All changes will be lost
--
-- Definition of Protection Warrior

DestroDummies.classWarriorProtection = DestroDummies.lastClassVal + 1;
DestroDummies.lastClassVal = DestroDummies.lastClassVal + 1;

local mIndexBase = DestroDummies.lastMutexIndex;

local function PickCombat()
    DestroDummies:analysisInit();
    local varthreatTank;
    local varthreatStatus;
    varthreatTank, varthreatStatus = DestroDummies:utilThreat()
    if not (varthreatTank) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Taunt"));
    end;
    if (not (DestroDummies:utilBuff(DestroDummies:xlateString("Commanding Shout"), 0, "player", "HELPFUL", nil))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Commanding Shout"));
    end;
    if (DestroDummies:spellReady(DestroDummies:xlateString("Shield Slam"))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Shield Slam"));
    end;
    if (not (DestroDummies:utilDebuff(DestroDummies:xlateString("Thunder Clap"), 0))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Thunderclap"));
    end;
    if (not (DestroDummies:utilDebuff(DestroDummies:xlateString("Demoralizing Shout"), 0))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Demoralizing Shout"));
    end;
    DestroDummies:analysisAdd(DestroDummies:xlateString("Revenge"));
    DestroDummies:analysisAdd(DestroDummies:xlateString("Devastate"));
    return DestroDummies:analysisPick(nil, nil);
end;

local function PickNoCombat()
    DestroDummies:analysisInit();
    if (not (DestroDummies:utilBuff(DestroDummies:xlateString("Commanding Shout"), 0, "player", "HELPFUL", nil))) then
        DestroDummies:analysisAdd(DestroDummies:xlateString("Commanding Shout"));
    end;
    return DestroDummies:analysisPick(nil, nil);
end;

-- populate our registries
DestroDummies.registry.decideCombat[DestroDummies.classWarriorProtection] = PickCombat;
DestroDummies.registry.decideNoCombat[DestroDummies.classWarriorProtection] = PickNoCombat;
DestroDummies.lastMutexIndex = mIndexBase + 0;
